name: workflowB.yml

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      release-tag:
        required: true
        type: string
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job-B:
    name: workflowB repo >> workflowB.yml >> Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=how" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword= are you" >> $GITHUB_OUTPUT
      - id: step3
        run: echo ${{ github.event.inputs.release-tag }}
